### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by muhdiboy** [grimm26/ytm_dislike_artist#5]
Hi,

I haven't used the script anymore. To my surprize it didn't work anymore.

This is the traceback I got:
```python
Traceback (most recent call last):
  File "/home/muhdi/scripts/./ytm_dislike_artist.py", line 109, in <module>
    main()
  File "/home/muhdi/scripts/./ytm_dislike_artist.py", line 103, in main
    dislike_all_songs(ytmusic, artist, args.dry_run)
  File "/home/muhdi/scripts/./ytm_dislike_artist.py", line 46, in dislike_all_songs
    albums = client.get_artist_albums(
  File "/home/muhdi/.local/lib/python3.10/site-packages/ytmusicapi/mixins/browsing.py", line 255, in get_artist_albums
    results = nav(response, SINGLE_COLUMN_TAB + SECTION_LIST_ITEM + GRID_ITEMS)
  File "/home/muhdi/.local/lib/python3.10/site-packages/ytmusicapi/navigation.py", line 81, in nav
    raise err
  File "/home/muhdi/.local/lib/python3.10/site-packages/ytmusicapi/navigation.py", line 75, in nav
    root = root[k]
KeyError: 'content'
``` 

ytmusicapi is the latest version 1.0.0
I've updated the headers_auth.json. The error appears after the countdown to dislike the songs.

**Comment by grimm26** [comment]
I got the same error when I tried, but I also hasn't used the script in a while. With ytmusicapi 1.0.0 I think the authentication part changed a bit and it assumes you auth file will be named oauth.json. I reauthenticated and used that file and it worked fine. I updated the README in the project here with that info and updated the script as well. Your oauth may also have expired or something.

Short answer, pull the newest version of my script, generate new authentication according to https://ytmusicapi.readthedocs.io/en/stable/setup/oauth.html
